/pullingOil/information/getWellName
/pullingOil/oilTank/{id}
/vehiclePullingOil/vehicle/getCarIdByUserName
/workflow/oil/driverAddWorkOrder
/task/list
/task/formDataShow/{taskID}
/task/formDataSave/{taskID}
/workflow/oil/list



### 
var url = http://60.30.245.242:28800
### list
http://60.30.245.242:28800/activiti/task/list?pageNum=1&pageSize=50 HTTP/1.1
username: wangweiwei
org_code: 0302
token: Bearer eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbl91c2VyX2tleSI6IjNkNjgzMmExLWZlNGItNDM3My1hMjcyLTE3NzM2NDU3MTFkYiJ9.oC3XTNzu1m6ndHVvPvNe1etf3WUaFhurxUEsF0jG_3xbAlbOQTuy0wGioVVKr0eFxsjOxi3rHN5fL6V3YLRyEw'
### getWellName
POST http://60.30.245.242:28800/activiti/pullingOil/information/getWellName HTTP/1.1
username: wangweiwei
org_code: 0302
token: Bearer eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbl91c2VyX2tleSI6IjNkNjgzMmExLWZlNGItNDM3My1hMjcyLTE3NzM2NDU3MTFkYiJ9.oC3XTNzu1m6ndHVvPvNe1etf3WUaFhurxUEsF0jG_3xbAlbOQTuy0wGioVVKr0eFxsjOxi3rHN5fL6V3YLRyEw'
###oilTank
POST http://60.30.245.242:28800/activiti/pullingOil/oilTank/6328 HTTP/1.1
username: wangweiwei
org_code: 0302
token: Bearer eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbl91c2VyX2tleSI6IjNkNjgzMmExLWZlNGItNDM3My1hMjcyLTE3NzM2NDU3MTFkYiJ9.oC3XTNzu1m6ndHVvPvNe1etf3WUaFhurxUEsF0jG_3xbAlbOQTuy0wGioVVKr0eFxsjOxi3rHN5fL6V3YLRyEw'
### getCarIdByUserName
POST http://60.30.245.242:28800/activiti/vehiclePullingOil/vehicle/getCarIdByUserName HTTP/1.1
username: wangweiwei
org_code: 0302
token: Bearer eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbl91c2VyX2tleSI6IjNkNjgzMmExLWZlNGItNDM3My1hMjcyLTE3NzM2NDU3MTFkYiJ9.oC3XTNzu1m6ndHVvPvNe1etf3WUaFhurxUEsF0jG_3xbAlbOQTuy0wGioVVKr0eFxsjOxi3rHN5fL6V3YLRyEw'

{
  
}
### driverAddWorkOrder
POST http://60.30.245.242:28800/activiti//workflow/oil/driverAddWorkOrder HTTP/1.1
username: wangweiwei
org_code: 0302
token: Bearer eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbl91c2VyX2tleSI6IjNkNjgzMmExLWZlNGItNDM3My1hMjcyLTE3NzM2NDU3MTFkYiJ9.oC3XTNzu1m6ndHVvPvNe1etf3WUaFhurxUEsF0jG_3xbAlbOQTuy0wGioVVKr0eFxsjOxi3rHN5fL6V3YLRyEw'



###
http://60.30.245.242:28800/img/

###
http://60.30.245.242:28800/moduleActiviti/task/list


### 
POST http://60.30.245.242:28800/moduleActiviti/task/list?pageNum=1&pageSize=50
content-type: application/json

{
  "pageNum":1,
  "pageSize":50
}


###

POST http://60.30.245.242:28800/f-app-inspection-record/getFAppInspectionRecordList HTTP/1.1
content-type: application/json

{
  "inspectionType": 3,
  "pageNo": 1,
  "pageSize":20,
  "terminalNo": "2",
  "userName":"gsman"
}